In [ ]:
import pandas as pd

In [86]:
df1= pd.read_excel('../data/raw/online_retail_II.xlsx', sheet_name='Year 2009-2010')
df2=pd.read_excel('../data/raw/online_retail_II.xlsx', sheet_name='Year 2010-2011')
df_all = pd.concat([df1,df2], ignore_index=True)

In [87]:
df_all.columns = df_all.columns.str.strip()
df_all.columns = df_all.columns.str.replace(' ', '_')
df_all.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer_ID', 'Country'],
      dtype='object')

In [89]:
df_all = df_all[df_all['Price'] > 0]

In [88]:
df_all['TotalSales'] = df_all['Quantity'] * df_all['Price']
df_all.head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer_ID,Country,TotalSales
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [110]:
df_all['Customer_ID'] = df_all['Customer_ID'].astype('Int64')
df_all['StockCode'] = df_all['StockCode'].astype(str)

In [111]:
df_all.to_csv('../data/processed/retail_with_returns.csv', index=False)

In [114]:
df_all.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer_ID,Country,TotalSales
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [ ]:
df_all.shape

(1061164, 9)

In [ ]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1061164 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1061164 non-null  object
 1   StockCode    1061164 non-null  object
 2   Description  1061164 non-null  object
 3   Quantity     1061164 non-null  int64
 4   InvoiceDate  1061164 non-null  datetime64[ns]
 5   Price        1061164 non-null  float64
 6   Customer_ID  824293 non-null   Int64
 7   Country      1061164 non-null  object
 8   TotalSales   1061164 non-null  float64
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 82.0+ MB

In [ ]:
missing_pct = df_all.isna().sum()*100/len(df_all)
missing_pct[missing_pct > 0]

Customer_ID    22.321809
dtype: float64

In [ ]:
quantity_over_zero = df_all[df_all['Quantity'] > 0]
quantity_over_zero.shape

(1041671, 9)

In [ ]:
price_over_zero = quantity_over_zero[quantity_over_zero['Price'] > 0]
price_over_zero.shape

(1041671, 9)

In [ ]:
df_clean = quantity_over_zero[~quantity_over_zero['Invoice'].astype(str).str.startswith('C')]
df_clean.shape

(1041670, 9)

In [109]:
df_clean['TotalSales'] = df_clean['Quantity'] * df_clean['Price']
df_clean.to_csv('../data/processed/retail_cleaned.csv', index=False)

C:\Users\kitki\AppData\Local\Temp\ipykernel_25908\3894198325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['TotalSales'] = df_clean['Quantity'] * df_clean['Price']